// <auto-generated />
namespace EDI_Reports.Migrations.Jobs
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EDI_Reports_db_migrations_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EDI_Reports_db_migrations_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131517367_EDI_Reports_db_migrations_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
